# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8daa9f8560ed4b3f56d78d270b945c37ab720e2150b2b19ceef2742e6b734030789b13aaefb2507703c565cd855ba5c6308b56e0215c6ef461a275160896bbc

test:
  secret_key_base: aaae5db4e2c33736c77ec5158c641bec82da0ea3bdae6af1f64efc3f622cbb0834b31873f1c85e670c9dc47fa5dbd05173428bc4cbf1026d724fb51f7790c493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
